--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.78.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 4/26/2019 2:13:02 PM
-- Server version: 5.7.21
-- Client version: 4.1
--


--
-- Definition for database thrivedb
--
CREATE DATABASE IF NOT EXISTS thrivedb
CHARACTER SET latin1
COLLATE latin1_general_ci;

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE thrivedb;

--
-- Definition for table heterogeneity_metric
--
CREATE TABLE IF NOT EXISTS heterogeneity_metric (
  slide_name varchar(255) NOT NULL,
  region_name varchar(255) NOT NULL,
  branch_name varchar(255) NOT NULL,
  metric_name varchar(255) NOT NULL,
  metric_value double DEFAULT NULL,
  PRIMARY KEY (slide_name, region_name, branch_name, metric_name)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Dumping data for table heterogeneity_metric
--

-- Table thrivedb.heterogeneity_metric does not contain any data (it is empty)

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;